### ISSUE TITLE
units commands missing

### ISSUE THREAD

**Issue by RodolpheGohard** [on4r/wc3-customkeys-generator#8]
Hello,

I configured the UI with my french layout:

> azer
> qsdf
> wxcv

And only the first line is correctly bound, the other hotkeys are the default one.
For example, acolyte has R bound to both (R)epair and Attack (R)

Did I miss something ?

**Comment by on4r** [comment]
There is currently no support for **Repair**, **Build** and **Gather** "_Spells_" from the main workers.
Any other hero and unit spells should work fine. Are you sure all the other hotkeys are the default ones?
